### PR TITLE
remove thunk + update deps

### PR DESCRIPTION
**Pull request by enapupe**

### CODE REVIEW

**Comment by enapupe** [comment]
@dleitee I merged it by accident, could you review anyway? 
Not major stuff, I just removed unused deps (thunk) + updated other deps.

**Comment by dleitee** [comment]
@enapupe ok, no problem, but why did you remove redux-thunk? Didn't we use it?

**Comment by enapupe** [comment]
The boilerplate doesn't seem to need it. Individual projects might.
Could you check if MnH requires It?

**Comment by enapupe** [comment]
Nevermind! I did a revert on that change. We do need thunk every time we write an action in the following format:
```
// requires thunk
export const completePublisherSignup = (uid, payload) => (dispatch) => dispatch({
  type: COMPLETE_PUBLISHER_SIGNUP.ACTION,
  payload: accountService.activate(uid, payload),
})
```
versus 
```
// doesn't requires thunk
export const getUsersStats = () => ({
  type: GET_USERS_STATS.ACTION,
  payload: statsService.getUsersStats(),
})
```

**Comment by dleitee** [comment]
I know, but at MnH we use : 
```
export const completePublisherSignup = (uid, payload) => (dispatch, getState) => dispatch({
  type: COMPLETE_PUBLISHER_SIGNUP.ACTION,
  payload: accountService.activate(uid, payload),
})
```

**Comment by enapupe** [comment]
Yeah Yeah.. We gotta keep it.

**Pull request merged**
